### ISSUE TITLE
Video quality limited to 480p

### ISSUE THREAD

**Issue by eboye** [vbaicu/mMusicCast#11]
Hi, thanks for making this app ... I find it really useful. But the video on YT is limited to 480p no matter what video I play.

Is this a chromecast v1 limitiation or is there some tweaks I can make to make it work 1080p?

Here's the video quality options I have:

![image](https://user-images.githubusercontent.com/624357/54407833-aae07980-46df-11e9-89d1-0b99f6c0027b.png)

**Comment by eboye** [comment]
I just dug out it is due to proprietary codecs

**Comment by remixer-dec** [comment]
I had a similar problem and I found a solution, it's implemented in my fork of this app. Your screen size + window size + zoom factor are things that somehow affect available quality. So increasing zoomFactor in code and opening window in fullscreen mode, allows you to get up to 4K.
