### ISSUE TITLE
Load a custom receiver from localhost

### ISSUE THREAD

**Issue by flovan** [vbaicu/mMusicCast#14]
Hi there,

I stumbled upon your Electron cast implementation while looking for ways to circumvent the need to an actual casting device. I was wondering if you could spare me some time by seeing if my use-case could be supported..

I have a custom receiver application can serve itself on `localhost:3001`. I have a web app which implements the sender framework, and which will be sending a cast application ID over to load in the correct connected receiver app.

If I run your code as-is, I do see an mMusicCast entry show up under the available devices, but it says "Source not supported".

Do you think I could get it to work? Any pointers on doing so?

Any help is greatly appreciated! Thank you for your time.

**Comment by kobeya** [comment]
Hi flovan,

if you develop something throug google cast SDK or refer google cast example?
That need chromecast or Android TV to bring up

**Comment by flovan** [comment]
Yeah I thought so, but a man can dream right 😉 
Thank you for getting back to me, I'll close this issue.
