### ISSUE TITLE
Is there any documentation as to how the code works?

### ISSUE THREAD

**Issue by CLOVIS-AI** [vbaicu/mMusicCast#16]
Hi, I'm wondering if there is any explanation of how the code works and how to add new apps?

I am really interested by this project, and depending on how adding apps is done, I might fork it to add new features (Google Photos, stuff like that).

Is there an explanation somewhere as to how it works?

**Comment by vbaicu** [comment]
Hi,
Unfortunately I did not created any docs and currently I'm not having the necessary time to do it. 
The code is not complex, maybe using the youtube app as an example and having breakpoints will help you understand it faster :)

**Comment by CLOVIS-AI** [comment]
Thanks, I'll take a look ^^
