### ISSUE TITLE
Won't start (open media vault)

### ISSUE THREAD

**Issue by TGC-TECH** [vbaicu/mMusicCast#4]
So I think a lot of the problems I am having comes from the fact the OMV is a terrible build of Debian that is missing many packages that people assume you already have installed but now after spending a half hour trying to install mMusicCast it won't start and exists saying:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mMusicCast@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mMusicCast@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-13T20_58_31_035Z-debug.log
root@HP-Plex:~/mMusicCast# npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mMusicCast@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mMusicCast@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I assume I am missing some dependency required to start mMC but I don't know what

**Comment by vbaicu** [comment]
Hello,
Your problem seems to be starting the electron itself, not the actual code of this app.
Electron is the platform on which mmusiccast runs, it provides a webview, runtime, and access to computer hardware. I had issues with electron on before, always some dependency that was missing.
I suggest cloning the electron quick start repo and trying to run it (https://github.com/electron/electron-quick-start) 
I don't know if it's the case, but if you are trying to run the app via ssh,  electron won't find the display to render on so you'll need to run this command first `export DISPLAY=:0`

This might also be useful : https://github.com/electron/electron-quick-start/issues/117

**Comment by TGC-TECH** [comment]
I reinstalled electron and I am getting the same thing. Here is the terminal output is this helps
Xlib:  extension "RANDR" missing on display ":10.0".
morgan deprecated undefined format: specify a format server.js:34:9
morgan deprecated default format: use combined format server.js:34:9
body-parser deprecated bodyParser: use individual json/urlencoded middlewares server.js:35:9
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:105:29
192.168.1.64
Registered App: ChromeCast
Registered App: YouTube
Express server listening on port 8008
Xlib:  extension "XInputExtension" missing on display ":10.0".
Xlib:  extension "RANDR" missing on display ":10.0".
Xlib:  extension "XInputExtension" missing on display ":10.0".
Xlib:  extension "XInputExtension" missing on display ":10.0".
::ffff:192.168.1.63 - - [Sun, 17 Jun 2018 16:02:46 GMT] "GET /ssdp/device-desc.xml HTTP/1.1" 200 1080 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.139 Chrome/66.0.3359.139 Safari/537.36"
::ffff:192.168.1.33 - - [Sun, 17 Jun 2018 16:03:01 GMT] "GET /ssdp/device-desc.xml HTTP/1.1" 200 1080 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
::ffff:192.168.1.13 - - [Sun, 17 Jun 2018 16:03:15 GMT] "GET /ssdp/device-desc.xml HTTP/1.1" 200 1080 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
